In [3]:
import numpy as np
a = np.array([1.0,2.0,3.0,4.0,5.0], dtype = "i")
b = np.array((1,2,3,4,5))

print(a)
print(b)
print(type(a))
print(type(b))
print(a.dtype)
print(b.dtype)

[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int32
int64


In [4]:
import numpy as np
c = np.array([1,2,3,4,5])
c.dtype

dtype('int64')

In [5]:
def love():
    return "I am in Love"
love()

'I am in Love'

In [6]:
print(a)

[1 2 3 4 5]


In [7]:
print(b)

[1 2 3 4 5]


In [8]:
d = np.array ([1,2,3,4,5,6]) #one dimensional array
d.ndim #used to check the dimension

1

In [9]:
e = np.array ([[1,2,3],[1,2,3]]) #this is a 2dimensional array. its like a concatenated list
e.ndim

2

In [10]:
f = np.array ([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
f.ndim

2

In [11]:
g = np.array ([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
g.ndim


3

In [12]:
d[1] #accessing a list

np.int64(2)

ACCESSING A NUMPY ARRAY

In [13]:
cc = np.array([1,2,3,4,5])
print(cc[2])

3


In [14]:
h = np.array([[1,2,3], [4,5,6]])
print(h[0,1])

2


In [15]:
print(f[2,2])

9


In [16]:
print(f[3,1])

11


In [17]:
print(g[1,1,2])

12


0 dimensional array


In [18]:
i = np.array(1)
i.ndim

0

methods in numpy

shape -  it is a method that tells you the number of dimension and the size of each axis (number of elements)
dimension is used interchangeably with axis except in the case of one dimension because it is just one acis eg: 4 axis = 4 dimension
-shape returns a tuple

In [19]:
j = np.array([1,2,3,4,5,6])
k = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
l = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

j.ndim
print(k)
print(l)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [20]:
j.shape


(6,)

In [21]:
k.shape

(4, 3)

In [22]:
l.shape

(2, 2, 3)

the number of elements returned by shape is equal to the number of dimensional array 


In [23]:
j.shape

(6,)

indexing the method shape, simply returns or prints out the element in that position in the returned tuple


In [24]:
k.shape[0]

4

In [25]:
l.shape[0]

2

In [26]:
tup = [6,4,5]
type(tup)
tup[1]

4

In [27]:
tup1 = j.shape
print(tup1)

(6,)


In [28]:
tup2 = k.shape
print(tup2)
print(tup2[1])

(4, 3)
3


a method always start with a parentheisis
to access an imported library we need to attah a method


Arange is used in creating a range in numpy
using the .arange method u eliminate the process of listing out numbers using the .arrary method.
eg np.array([1,2,3]), but np.arange(3) will be equal to 0-3. and ensure to call the variable or print it.

In [29]:
m = np.arange(100)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
m.ndim

1

In [31]:
n = np.arange(20,100) #the second parameter creates a range 20 -100
n

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
import random as rn
o = rn.randint(0,100)
o
#the normal random library is written like this

78

but the random library in numpy becomes a method cause numpy its a library on its own and its accesd like this

In [33]:
p = np.random.randint(20,100) #cause it uses randint it will become an integer instead of an array.
p #or u cam print(p)

45

so to combat it from become an integer with randint we use random.randn(puts negative number) and random.rand

In [34]:
q = np.random.randn(100)
q

array([-0.33146854,  0.1931801 , -0.56694246,  0.01523385, -0.22575547,
        0.32151266, -0.62981544, -1.03940766, -0.04168168, -0.65407366,
       -0.68107416,  0.56998862,  0.42972107, -1.06400959,  0.40711486,
       -0.80414036, -0.45468086, -1.64873548, -0.47654653, -1.34723125,
       -2.32962398, -1.21136639,  1.4671254 ,  0.64833564,  0.22214469,
       -0.11585435, -0.80992996, -0.06947991, -0.22742766, -0.39042304,
        0.20427205,  0.1137888 , -0.44402002,  0.16404968,  0.288063  ,
        0.18553144,  1.70021629,  0.04201427, -0.39536293,  0.31381331,
       -0.77300175,  2.44903157, -0.33810543,  1.42981847, -0.60879581,
        1.21254113, -1.5475174 , -1.04435487, -0.84495112,  0.0938624 ,
        0.27798185, -0.75044762, -1.30482762,  2.47089952,  0.64277348,
        0.58756543, -0.48281026,  1.22307648,  1.34466338,  2.08588322,
       -1.48442397, -1.05773336, -0.09654435, -0.85212491, -0.55103569,
        0.32808541, -2.5030581 ,  0.20988884, -0.62994948,  0.45

In [35]:
type(q)

numpy.ndarray

In [36]:
import matplotlib.pyplot as mb
mb.hist(q)

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
type(q)

numpy.ndarray

In [ ]:
q.ndim

1

using .rand and .randn in multidimension

In [ ]:
r = np.random.rand(2)
r

array([0.62772713, 0.79658291])

In [ ]:
s = np.random.rand(2,4)
s

array([[0.65640007, 0.05818901, 0.47979401, 0.75501234],
       [0.46662097, 0.88634245, 0.79732067, 0.73712493]])

In [ ]:
s.ndim

2

In [ ]:
t = np.random.rand(3,5,2) #3 dimension, 5 axis in each dimension and 2 element in each axis
t

array([[[0.81847295, 0.74712302],
        [0.96274037, 0.98098989],
        [0.95302532, 0.48717783],
        [0.7848161 , 0.32614444],
        [0.47966319, 0.64022706]],

       [[0.54475166, 0.36368863],
        [0.53413663, 0.93404454],
        [0.39040203, 0.27259542],
        [0.45137202, 0.8378647 ],
        [0.97493407, 0.648535  ]],

       [[0.87324228, 0.45619423],
        [0.72479996, 0.69934464],
        [0.92416578, 0.22207754],
        [0.58289557, 0.81743563],
        [0.26170883, 0.54528158]]])

In [ ]:
t.ndim

3

4 dimensional array

In [ ]:
first_4_dim_array = np.array([[[[123, 123]], [[123, 123]]], [[[123, 123]], [[123, 123]]]])
first_4_dim_array.ndim

4

In [ ]:
to = np.random.rand(4,3,2,1)
to

array([[[[0.61602307],
         [0.87543816]],

        [[0.23285627],
         [0.6150839 ]],

        [[0.60784915],
         [0.63339342]]],


       [[[0.93080088],
         [0.31952426]],

        [[0.60410545],
         [0.50737058]],

        [[0.1848256 ],
         [0.35040039]]],


       [[[0.30685335],
         [0.0325573 ]],

        [[0.51685234],
         [0.43764677]],

        [[0.03061813],
         [0.71533893]]],


       [[[0.17267781],
         [0.04573203]],

        [[0.94371712],
         [0.84986446]],

        [[0.11934584],
         [0.18264268]]]])

In [ ]:
to.ndim

4

In [ ]:
to.shape

(4, 3, 2, 1)

.reshape method

In [ ]:
u = np.arange(100).reshape(4,25) #u cant list out range 100 then reshape (it wont change the dimension), you have to write it in one line.
u

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
u.shape

(4, 25)

In [ ]:
u.ndim

2

In [ ]:
u.shape

(4, 25)

In [ ]:
list = [1,2,3,4]
list[2] =10
list

[1, 2, 10, 4]

In [39]:
v = np.arange(20,100).reshape(4,20)
v


array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [ ]:
w = np.random.rand(3,4)
w

array([[0.69010015, 0.80007336, 0.89379994, 0.96199384],
       [0.52468631, 0.47622147, 0.42011724, 0.81774927],
       [0.49802255, 0.62657033, 0.26295269, 0.77284414]])

In [ ]:
num = 20.4523
round(num,1) #rounds up to whole number or decimal place depending on the number after num

20.5

round method

In [ ]:
x = np.round(w)
x

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.]])

In [ ]:
y = 10 * np.random.rand(3,4)
y

array([[2.42541119, 2.13885403, 5.11700475, 3.43165309],
       [3.63630395, 8.13764652, 9.72169475, 1.77563235],
       [7.46977592, 9.08677412, 7.81417425, 0.5440158 ]])

zeros and ones method
the zeros print only zeros and ones print only ones

In [ ]:
z = np.zeros(3)
aa = np.ones(5)
z

array([0., 0., 0.])

In [ ]:
aa

array([1., 1., 1., 1., 1.])

numpy slicing

In [ ]:
my_list = [1,2,3,4,5,6,7,8]
my_list[3:5] #this is normal python

[4, 5]

Numpy slicing methods
A[start:end: step]
a[1:5] #index 1 till 5 but not 5
a[:5] #index 0 till 5
a[2:] #index 2 till end including last element
a[::-1] #from end till start (reverse the array)
a[::2]
a[::2,:] ?

In [ ]:
A = np.round(10*np.random.rand(3,6))
A

array([[1., 2., 2., 3., 2., 1.],
       [5., 6., 8., 3., 5., 2.],
       [3., 7., 7., 4., 7., 1.]])

In [ ]:
print(A[0,2])

2.0


In [ ]:
A[1:3] #indexes 1 till 3 but not 3

array([[5., 6., 8., 3., 5., 2.],
       [3., 7., 7., 4., 7., 1.]])

In [ ]:
A[:3] #indesxes 0 till 3 

array([[1., 2., 2., 3., 2., 1.],
       [5., 6., 8., 3., 5., 2.],
       [3., 7., 7., 4., 7., 1.]])

In [ ]:
A[1:] #indexes 1 till end

array([[5., 6., 8., 3., 5., 2.],
       [3., 7., 7., 4., 7., 1.]])

In [ ]:
A[::-1] #reverses the list

array([[3., 7., 7., 4., 7., 1.],
       [5., 6., 8., 3., 5., 2.],
       [1., 2., 2., 3., 2., 1.]])

In [ ]:
A[::2] #skips a line or axis 

array([[1., 2., 2., 3., 2., 1.],
       [3., 7., 7., 4., 7., 1.]])

In [ ]:
A[2,3]

np.float64(4.0)

In [ ]:
B = np.arange(50)
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
C = B[2:20]
C

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
C[5] = 100
C

array([  2,   3,   4,   5,   6, 100,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19])

In [ ]:
B

array([  0,   1,   2,   3,   4,   5,   6, 100,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49])

In [ ]:
D = np.round(10*np.random.rand(5,4))
D

array([[ 6.,  5.,  8.,  3.],
       [ 0.,  3.,  0.,  1.],
       [10.,  3.,  2.,  5.],
       [ 9.,  4.,  8.,  7.],
       [ 4.,  3.,  3., 10.]])

In [ ]:
D[:2]

array([[6., 5., 8., 3.],
       [0., 3., 0., 1.]])

In [ ]:
D[1:3]

array([[ 0.,  3.,  0.,  1.],
       [10.,  3.,  2.,  5.]])

In [ ]:
D[1:3,2:4] #slicing a matrix out of a matrix or concatenated slicing

array([[0., 1.],
       [2., 5.]])

In [ ]:
D[3:5,0:2]

array([[9., 4.],
       [4., 3.]])

In [ ]:
D[2:4,1:3]

array([[3., 2.],
       [4., 8.]])

In [ ]:
D[2:5,2:4]

array([[ 2.,  5.],
       [ 8.,  7.],
       [ 3., 10.]])

Transpose method- .T #changes roles to column and vice versa

In [ ]:
E = np.round(10*np.random.rand(5,4))
E

array([[ 7.,  4.,  5.,  6.],
       [10.,  2.,  8.,  7.],
       [ 0.,  0.,  1.,  3.],
       [ 6.,  8.,  2.,  6.],
       [ 6.,  6.,  6.,  7.]])

In [ ]:
E.T 

array([[ 7., 10.,  0.,  6.,  6.],
       [ 4.,  2.,  0.,  8.,  6.],
       [ 5.,  8.,  1.,  2.,  6.],
       [ 6.,  7.,  3.,  6.,  7.]])

sort method - sort(axis) axis 0 = columns axis 1= rows


In [ ]:
E.sort(axis=0)
E

array([[ 0.,  0.,  1.,  3.],
       [ 6.,  2.,  2.,  6.],
       [ 6.,  4.,  5.,  6.],
       [ 7.,  6.,  6.,  7.],
       [10.,  8.,  8.,  7.]])

In [ ]:
E.sort(axis=1)
E

array([[ 0.,  0.,  1.,  3.],
       [ 2.,  2.,  6.,  6.],
       [ 4.,  5.,  6.,  6.],
       [ 6.,  6.,  7.,  7.],
       [ 7.,  8.,  8., 10.]])

In [ ]:
F = np.round(10*np.random.rand(3,2,4))
F

array([[[ 5.,  4.,  0.,  1.],
        [ 2.,  7.,  6.,  1.]],

       [[ 7.,  8.,  5.,  4.],
        [ 3.,  0.,  2.,  5.]],

       [[ 2.,  4.,  9.,  6.],
        [ 0.,  8., 10.,  3.]]])

How to 

In [ ]:
F[1,1,2]

np.float64(2.0)

In [ ]:
F[[0]]

array([[[5., 4., 0., 1.],
        [2., 7., 6., 1.]]])

In [ ]:
F[[0,1]]

array([[[5., 4., 0., 1.],
        [2., 7., 6., 1.]],

       [[7., 8., 5., 4.],
        [3., 0., 2., 5.]]])

In [ ]:
F[[0,1,2]]

array([[[ 5.,  4.,  0.,  1.],
        [ 2.,  7.,  6.,  1.]],

       [[ 7.,  8.,  5.,  4.],
        [ 3.,  0.,  2.,  5.]],

       [[ 2.,  4.,  9.,  6.],
        [ 0.,  8., 10.,  3.]]])

In [ ]:
G = np.round(10*np.random.rand(5,4))
G

array([[7., 3., 1., 5.],
       [9., 3., 6., 1.],
       [9., 9., 9., 6.],
       [6., 6., 5., 5.],
       [2., 1., 7., 4.]])

In [ ]:
G[[1,2]]

array([[9., 3., 6., 1.],
       [9., 9., 9., 6.]])

In [ ]:
G[[3]]

array([[6., 6., 5., 5.]])

In [ ]:
H = np.arange(50)
H

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
I = H[H<25]
I

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
J = H[H>25]
J

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

& SIGN


In [ ]:
K = H[(H>10) & (H<30)]
K

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

Broadcasting in numpy - this is simply when you change the elements of a matrix with one single element 

In [ ]:
#Broadcasting with +
L = np.round(10*np.random.rand(3,2))
L

array([[8., 3.],
       [8., 7.],
       [1., 4.]])

In [ ]:
L = L + 5
L #This adds 5 to each elemrnt in the array

array([[13.,  8.],
       [13., 12.],
       [ 6.,  9.]])

In [ ]:
#Broadcasting with -
L = L - 5
L

array([[8., 3.],
       [8., 7.],
       [1., 4.]])

In [ ]:
#Broadcasting with *
L = L * 2
L


array([[16.,  6.],
       [16., 14.],
       [ 2.,  8.]])

In [ ]:
#Broadcasting with /
L = L/3
L = np.round(L,2)
L

array([[5.33, 2.  ],
       [5.33, 4.67],
       [0.67, 2.67]])

In [ ]:
M = np.arange(0, 10).reshape(2,5)
M

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
N = np.arange(10, 20).reshape(2,5)
N

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
O = M + N
O

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [ ]:
P = np.arange(10, 20).reshape(2,5)
P

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
Q = np.arange(10, 25).reshape(3,5)
Q

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

R = P + Q
# This will not broadcast together because of the difference in shapes


In [ ]:
O = M - N
O

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [ ]:
O = M * N
O

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

In [ ]:
O = M / N
O

array([[0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429],
       [0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421]])

Hstack & Vstack

In [ ]:
S = np.arange(0, 10).reshape(2,5)
S

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
T = np.arange(10, 20).reshape(2,5)
T

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
U = np.hstack((S, T))
U  #this combines two array horizontally 


array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [ ]:
U = np.vstack((S, T))
U #this combines two array vertically

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
V = np.random.rand(1000000)


In [ ]:
%timeit sum(v)

6.89 μs ± 598 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
%timeit np.sum(v)

7.38 μs ± 325 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
