PANDAS - SERIES 

In [183]:
import pandas as pd 

In [184]:
A = pd.Series(["ada", "roberta", 300 , "christain"], index=["a", "b", "c", "d"])

type(A)


pandas.Series

In [185]:
A.values


array(['ada', 'roberta', 300, 'christain'], dtype=object)

In [186]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [187]:
type(A.values)

numpy.ndarray

In [188]:
type(A.index)

pandas.Index

In [189]:
B = pd.Series(["ada", "roberta", 300 , "christain"], index=["a", "b", "c", "d"])

In [190]:
B["a"]

'ada'

In [191]:
B["a" : "c"]

a        ada
b    roberta
c        300
dtype: object

In [192]:
grades_dict = {"A":20, "A-": 15, "B": 10}
C = pd.Series(grades_dict)
type(C)

pandas.Series

In [193]:
C.index

Index(['A', 'A-', 'B'], dtype='str')

In [194]:
C.values    

array([20, 15, 10])

In [195]:
C.values

array([20, 15, 10])

In [196]:
mark_dict = {"A":20, "A-": 15, "B": 10, "C": 5}

mark = pd.Series(mark_dict)
mark 

A     20
A-    15
B     10
C      5
dtype: int64

In [197]:
mark.index

Index(['A', 'A-', 'B', 'C'], dtype='str')

In [198]:
mark.values

array([20, 15, 10,  5])

In [199]:
mark["A": "B"]

A     20
A-    15
B     10
dtype: int64

In [200]:
mark["A"]

np.int64(20)

In [201]:
mark[0:2]

A     20
A-    15
dtype: int64

PANDA DATAFRAMES 

In [202]:
grades_dict = {"A":20, "A-": 15, "B": 10}
mark_dict = {"A":20, "A-": 15, "B": 10, "C": 5}

grades = pd.Series(grades_dict) #this is a series
mark = pd.Series(mark_dict) #this is a series

In [203]:
D = pd.DataFrame({"Grades": grades, "Marks": mark})
D 
# NaN - means None 

,Grades,Marks
A,20.0,20
A-,15.0,15
B,10.0,10
C,NaN,5


In [204]:
grades_dict = {"A":20, "A-": 15, "B": 10}
mark_dict = {"C":20, "C-": 15, "D": 10}
grades = pd.Series(grades_dict) #this is a series
mark = pd.Series(mark_dict) #this is a series

In [205]:
E = pd.DataFrame({"Marks" : mark, "Grades" : grades})
E

,Marks,Grades
A,NaN,20.0
A-,NaN,15.0
B,NaN,10.0
C,20.0,NaN
C-,15.0,NaN
D,10.0,NaN


In [206]:
E.T

,A,A-,B,C,C-,D
Marks,NaN,NaN,NaN,20.0,15.0,10.0
Grades,20.0,15.0,10.0,NaN,NaN,NaN


In [207]:
E.index

Index(['A', 'A-', 'B', 'C', 'C-', 'D'], dtype='str')

In [208]:
E.values

array([[nan, 20.],
       [nan, 15.],
       [nan, 10.],
       [20., nan],
       [15., nan],
       [10., nan]])

In [209]:
grades_dict = {"A":20, "A-": 15, "B": 10}
mark_dict = {"A":20, "A-": 15, "B": 10}
grades = pd.Series(grades_dict) #this is a series
mark = pd.Series(mark_dict) #this is a series

F = pd.DataFrame({"Marks" : mark, "Grades" : grades})
F

,Marks,Grades
A,20,20
A-,15,15
B,10,10


ACCESSING ELEMENTS IN A PANDA DATAFRAMES 

In [210]:
F.values[2,0]

np.int64(10)

In [211]:
F.values[1,1]

np.int64(15)

In [212]:
F.values[2,1]

np.int64(10)

In [213]:
F = pd.DataFrame({"Marks" : mark, "Grades" : grades})
F

,Marks,Grades
A,20,20
A-,15,15
B,10,10


In [214]:
F.columns

Index(['Marks', 'Grades'], dtype='str')

In [215]:
F.index 

Index(['A', 'A-', 'B'], dtype='str')

In [216]:
F.values

array([[20, 20],
       [15, 15],
       [10, 10]])

In [217]:
Total_dict = {"A": 100, "A-": 50, "B": 70}
Total_dict

{'A': 100, 'A-': 50, 'B': 70}

Adding a column(dict) to a dataframe 

In [218]:
F["Total"] = Total_dict

In [219]:
F

,Marks,Grades,Total
A,20,20,100
A-,15,15,50
B,10,10,70


Performing basic operations with existing columns while adding the result as a column to the dataframe

In [220]:
F["Average"] = (F["Marks"] + F["Grades"]) / 2

In [221]:
F

,Marks,Grades,Total,Average
A,20,20,100,20.0
A-,15,15,50,15.0
B,10,10,70,10.0


Deleting a column from a dataframe 

In [222]:
F["diff"] = (F["Total"] - F["Grades"])
F

,Marks,Grades,Total,Average,diff
A,20,20,100,20.0,80
A-,15,15,50,15.0,35
B,10,10,70,10.0,60


In [223]:
F.pop("diff")


A     80
A-    35
B     60
Name: diff, dtype: int64

In [224]:
F

,Marks,Grades,Total,Average
A,20,20,100,20.0
A-,15,15,50,15.0
B,10,10,70,10.0


In [225]:
del F["Average"]


In [226]:
F

,Marks,Grades,Total
A,20,20,100
A-,15,15,50
B,10,10,70


In [227]:
G = F[F["Marks"]> 10]
G 

,Marks,Grades,Total
A,20,20,100
A-,15,15,50


In [228]:
H = F[F["Grades"]> 10]
H

,Marks,Grades,Total
A,20,20,100
A-,15,15,50


NaN - replacing NaN 

In [229]:
I_dict = {"B": "boy", "C": "cat", "D": "dog"}
j_dict = {"C": "cat", "D": "dog", "F": "french"}

I = pd.Series(I_dict)
J = pd.Series(j_dict)

k = pd.DataFrame({"I": I, "J": J})

In [230]:
k

,I,J
B,boy,NaN
C,cat,cat
D,dog,dog
F,NaN,french


In [231]:
L = k.fillna(10)
L

,I,J
B,boy,10
C,cat,cat
D,dog,dog
F,10,french


In [232]:
L

,I,J
B,boy,10
C,cat,cat
D,dog,dog
F,10,french


you dont necessarily need to create a panda dataframe from a series, you can just stack several database

In [233]:
I_dict = {"B": "boy", "C": "cat", "D": "dog"}
j_dict = {"C": "cat", "D": "dog", "f": "french"}

M = pd.DataFrame([I_dict, j_dict])
M


,B,C,D,f
0,boy,cat,dog,NaN
1,NaN,cat,dog,french


In [234]:
N = pd.DataFrame([{"B": "boy", "C": "cat", "D": "dog"}, {"C": "cat", "D": "dog", "F": "french"}])
N

,B,C,D,F
0,boy,cat,dog,NaN
1,NaN,cat,dog,french


In [235]:
O = pd.DataFrame([{"B": "boy", "C": "cat", "D": "dog"}, {"C": "cat", "D": "dog", "F": "french"}], index=["Choice 1", "Choice 2"])
O


,B,C,D,F
Choice 1,boy,cat,dog,NaN
Choice 2,NaN,cat,dog,french


In [236]:
P = pd.DataFrame([{"B": "boy", "C": "cat", "D": "dog"}, {"C": "cat", "D": "dog", "F": "french"}], index=["Choice 1", "Choice 2"])

Q  = pd.DataFrame([{"B": "bat", "C": "church", "D": "dance"}], index=["choice 3"])


concatenating two panda dataframe

In [238]:
R = pd.concat([P, Q])
R

,B,C,D,F
Choice 1,boy,cat,dog,NaN
Choice 2,NaN,cat,dog,french
choice 3,bat,church,dance,NaN
